// trainerStore.ts
import { create } from "zustand";
import { Trainer } from "../types/TrainerTypes";
interface TrainerState {
  trainers: Trainer[];
  setTrainers: (trainers: Trainer[]) => void;
  shortlistedTrainers:Trainer[]
}

// Example data extracted/derived from your CSV screenshot
const initialTrainers: Trainer[] = [
  {
    trainerID: 1,
    name: "Sonali Nair",
    skill: "Model-Based Dev",
    tool: "Code Generation",
    technology: "Yocto",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    source: "Reference",
    prequalified: "No",
    trainerType: "Individual",
    ratings: 4.2,
  },
  {
    trainerID: 2,
    name: "Sohail Iqbal",
    skill: "Control Systems",
    tool: "Profiling Tools",
    technology: "PetaLinux",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    source: "Portal",
    prequalified: "Yes",
    trainerType: "Individual",
    ratings: 4.0,
  },
  {
    trainerID: 3,
    name: "Jagriti Reddy",
    skill: "HIL Testing",
    tool: "Real-Time Simulation",
    technology: "QNX",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    source: "Agency",
    prequalified: "No",
    trainerType: "Institute",
    ratings: 4.5,
  },
  {
    trainerID: 4,
    name: "Deepali Singh",
    skill: "Signal Processing",
    tool: "DSP",
    technology: "Signal Theory",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    source: "Reference",
    prequalified: "Yes",
    trainerType: "Individual",
    ratings: 4.3,
  },
  {
    trainerID: 5,
    name: "Mikram Singh",
    skill: "Control Systems",
    tool: "State Machines",
    technology: "Control Theory",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    source: "Portal",
    prequalified: "No",
    trainerType: "Individual",
    ratings: 3.9,
  },
  {
    trainerID: 6,
    name: "Swati Agarwal",
    skill: "Safety Analysis",
    tool: "Cov Tools",
    technology: "Coverage",
    city: "Lucknow",
    state: "Uttar Pradesh",
    country: "India",
    source: "Reference",
    prequalified: "Yes",
    trainerType: "Institute",
    ratings: 4.1,
  },
  {
    trainerID: 7,
    name: "Advanced Automotive Institute",
    skill: "Model-Based Dev",
    tool: "AI/ML",
    technology: "TensorFlow",
    city: "Nagpur",
    state: "Maharashtra",
    country: "India",
    source: "Agency",
    prequalified: "No",
    trainerType: "Institute",
    ratings: 4.0,
  },
  {
    trainerID: 8,
    name: "Aj AI",
    skill: "AI/ML",
    tool: "TensorFlow",
    technology: "TensorFlow",
    city: "Kita",
    state: "Unknown",
    country: "Japan",
    source: "Portal",
    prequalified: "No",
    trainerType: "Institute",
    ratings: 4.8,
  },
  {
    trainerID: 9,
    name: "Nandita Tech",
    skill: "Data Logging",
    tool: "TestBench",
    technology: "TeardownHW",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    source: "Reference",
    prequalified: "Yes",
    trainerType: "Individual",
    ratings: 4.7,
  },
  {
    trainerID: 10,
    name: "DevSai Solutions",
    skill: "Data Logging",
    tool: "Data Loggers",
    technology: "StorageHW",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    source: "Portal",
    prequalified: "No",
    trainerType: "Individual",
    ratings: 3.5,
  },
  {
    trainerID: 11,
    name: "MST Innovations",
    skill: "Communication Protocols",
    tool: "CAN",
    technology: "CAN-DBC",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    source: "Agency",
    prequalified: "Yes",
    trainerType: "Institute",
    ratings: 4.0,
  },
  {
    trainerID: 12,
    name: "Sai Tutorials",
    skill: "SDLC",
    tool: "Jira",
    technology: "Confluence",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    source: "Portal",
    prequalified: "No",
    trainerType: "Individual",
    ratings: 3.8,
  },
  {
    trainerID: 13,
    name: "VIT Training Academy",
    skill: "Quality Assurance",
    tool: "Code Reviews",
    technology: "Quality Control",
    city: "Vellore",
    state: "Tamil Nadu",
    country: "India",
    source: "Reference",
    prequalified: "Yes",
    trainerType: "Institute",
    ratings: 4.9,
  },
  {
    trainerID: 14,
    name: "Abc Software Academy",
    skill: "Software Testing",
    tool: "Test Automation",
    technology: "Jenkins",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    source: "Portal",
    prequalified: "No",
    trainerType: "Institute",
    ratings: 4.2,
  },
  {
    trainerID: 15,
    name: "OnTime Software Center",
    skill: "Software Testing",
    tool: "CI/CD",
    technology: "Jenkins",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    source: "Reference",
    prequalified: "Yes",
    trainerType: "Individual",
    ratings: 3.9,
  },
  {
    trainerID: 16,
    name: "Deep Logic Institute",
    skill: "AI/ML",
    tool: "PyTorch",
    technology: "Python",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    source: "Agency",
    prequalified: "No",
    trainerType: "Institute",
    ratings: 4.3,
  },
  {
    trainerID: 17,
    name: "SoftSim Training",
    skill: "Simulation",
    tool: "Matlab",
    technology: "Simulink",
    city: "Lucknow",
    state: "Uttar Pradesh",
    country: "India",
    source: "Portal",
    prequalified: "Yes",
    trainerType: "Individual",
    ratings: 4.1,
  },
  {
    trainerID: 18,
    name: "VisionTek Institute",
    skill: "Architecture Modeling",
    tool: "SysML",
    technology: "UML",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    source: "Reference",
    prequalified: "No",
    trainerType: "Institute",
    ratings: 4.0,
  },
  {
    trainerID: 19,
    name: "SaiChakra Software Center",
    skill: "Architecture Modeling",
    tool: "SysML",
    technology: "Modelica",
    city: "Nagpur",
    state: "Maharashtra",
    country: "India",
    source: "Agency",
    prequalified: "No",
    trainerType: "Individual",
    ratings: 3.7,
  },
  {
    trainerID: 20,
    name: "Nisha Software Training",
    skill: "Software Modeling",
    tool: "UML Tools",
    technology: "ArchiMate",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    source: "Portal",
    prequalified: "Yes",
    trainerType: "Individual",
    ratings: 4.4,
  },
];

export const useTrainerStore = create<TrainerState>((set) => ({
  trainers: initialTrainers,
  shortlistedTrainers: initialTrainers.slice(0, 5),
  setTrainers: (trainers) => set({ trainers }),
}));
